¿A qué inversión le fue mejor en lo que va del 2022, dólar blue, UVA o UVI?

En lo que va del año 2022 decidimos comparar cual es la inversión que mejores rendimientos trajo a aquellas personas que decidieron confiar sus ahorros en dólar blue, UVA o UVI. Antes que desplegar cualquier análisis debemos saber de qué se trata cada una de estas. 

UVI: Unidades de Vivienda es un sistema de ahorro en "ladrillos". Es una unidad que se ajusta en pesos indexada por el índice de costos la Construcción. Si bien también se puede utilizar para ajustar créditos hipotecarios, hoy la banca pública lo ofrece como una forma de ahorro en metros cuadrados de vivienda. En donde se ahorra en UVI y se calcula que cada 1.000 unidades se adquieren un metro de construcción.

UVA: Unidad de Valor Adquisitivo ajustada por el índice Coeficiente de Estabilización de Referencia (CER), que es elaborado por el Banco Central de la República Argentina (BCRA) para medir la evolución de la inflación tomando como base el Índice de Precios al Consumidor (IPC) del INDEC. Por lo tanto, cada UVA tiene un valor en pesos que aumenta por medio del CER.

Dólar blue es el mercado informal o no regulado de la divisa norteamericana. 

En el grafico se puede observar en el eje ‘X’ el paso de los meses del 2022 luego en el eje ‘Y’ los índices de UVA, UVI y dólar blue. Todos los incides arrancan el 100 para hacer más fácil su comparación, el desempeño de cada uno es variado dependiendo de la época del año, en algunos meses el dólar blue estuvo por encima de los otros dos índices. Pero hoy concretamente quien está en primer puesto   el índice UVA con 72 puntos arriba segundo lugar seguido UVI con 55 y en tercer puesto el índice dólar blue con 43. 

Debemos pensar y tener en cuenta algunas consideraciones a la hora de decidir qué tipo de inversión vamos a realizar Es posible que alguna necesidad surja y nos veamos forzados a deshacernos de alguna porción de nuestra inversión. La flexibilidad que tiene el dólar de convertir en pesos es casi inmediata sin ningún tipo de penalidad alguna más que la cotización del día. 

En cuanto a plazo mínimo es de 90 días para UVA y de 180 días para UVI. Con la posibilidad de cancelar recién transcurrido el primer mes completo, es decir poder darlo por finalizarlo para cobrar los intereses al día número 31 desde que se lo inicio.  

Luego de los puntos mencionados anteriormente es importante saber qué tipo de gastos vamos a tener y cuál podría ser nuestra necesidad de hacernos lo más rápidamente de nuestro dinero para poder utilizarlo. ¿En el caso de que surja un imprevisto, podríamos esperar un mes para cancelar un plazo fijo? Si la respuesta es sí, lo más probables es que deberíamos ver la forma de fraccionar nuestro plazo fijo. Creando varios con un mes de diferencia   para disponer de algún dinero si deseamos gastarlo. De lo contrario podríamos hacer el plazo fijo a un mayor plazo. Si ninguna de las dos opciones anteriores te da tranquilidad entonces será el dólar blue tu mejor opción. ¿Cuál es la mejor inversión para vos teniendo en cuenta tu situación? Como decimos siempre, hacelo personal, contanos   porque elegiste una opción y no otra.

# Proximos pasos 

* Desde cuando hay datos uva y uvis --> esta en el bcra principales variables.  
* markdown 
* Bucar de que forma voy a contar esta historia y a quienes puntualmente. 
   * Profe ingles (sueldo variable no alquila  )
   * Empleado sueldo fijo alquila.
   * Ahorrista de USD200 /mes 
   * Ahorrista con USD20000

* TODO 
  * Pasar UVA a % que todo quede en base 100
  * Hacer proximos pasos
  * Buscar dolar oficial 
  * Comparar si la infacion mensual se puede sacar de UVAs
  * Como sacar la inflacion mensaul de BCRA https://www.bcra.gob.ar/PublicacionesEstadisticas/Principales_variables_datos.asp
  * Ver la relacion entre aumento del blue y el oficial
  * inversiones disponibles monto y plazo  minimo.

#¿Tenés 5k y no sabés en dónde invertir?

¿A qué  inversión le fue mejor en lo que va del 2022, dólar blue, UVA o UVIS? 

En lo que va del año 2022 decidimos comparar cual es la inversión que mejores rendimientos trajo a aquellas personas que decidieron confiar sus ahorros en dólar blue, UVA o UVIS. Antes que desplegar cualquier análisis debemos saber de qué se trata cada una de estas.

UVI: Unidades de Vivienda es un sistema de ahorro en "ladrillos". Es una unidad que se ajusta en pesos indexada por el índice de costos la Construcción. Si bien también se puede utilizar para ajustar créditos hipotecarios, hoy la banca pública lo ofrece como una forma de ahorro en metros cuadrados de vivienda. En donde se ahorra en UVI y se calcula que cada 1.000 unidades se adquieren un metro de construcción.

UVA: Unidad de Valor Adquisitivo ajustada por el índice Coeficiente de Estabilización de Referencia (CER), que es elaborado por el Banco Central de la República Argentina (BCRA) para medir la evolución de la inflación tomando como base el Índice de Precios al Consumidor (IPC) del INDEC. Por lo tanto, cada UVA tiene un valor en pesos que aumenta por medio del CER ?

Dólar blue es el mercado informal o no regulado de la divisa norteamericana.

In [ ]:
!pip install --upgrade plotly
!pip install jupyter-dash #TODO: es necesario? Que suma?

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (5.5.0)
Collecting plotly
  Downloading plotly-5.11.0-py2.py3-none-any.whl (15.3 MB)
     |████████████████████████████████| 15.3 MB 5.5 MB/s
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly) (8.1.0)
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 5.5.0
    Uninstalling plotly-5.5.0:
      Successfully uninstalled plotly-5.5.0
Successfully installed plotly-5.11.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting jupyter-dash
  Downloading jupyter_dash-0.4.2-py3-none-any.whl (23 kB)
Collecting dash
  Downloading dash-2.7.0-py3-none-any.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 7.1 MB/s
Requirement already satisfied: ipython in /usr/local/lib/python3.7/dist-packages (from jupyter-dash) (7.9.0)
Collecting ansi2html
  Downloading ansi2html-1.8.0-py3-none-any.whl (16 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from jupyter-dash) (2.23.0)
Requirement already satisfied: flask in /usr/local/lib/python3.7/dist-packages (from jupyter-dash) (1.1.4)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.7/dist-packages (from jupyter-dash) (5.3.4)
Collecting retrying
  Downloading retrying-1.3.3.tar.gz (10 kB)
Collecting nest-asyncio
  Downloading nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from ansi2html->jupyter-dash) (4.13.0)
Collecting dash-table==5.0.0
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Collecting dash-html-components==2.0.0
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Collecting dash-core-components==2.0.0
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from dash->jupyter-dash) (5.11.0)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from flask->jupyter-dash) (1.1.0)
Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.7/dist-packages (from flask->jupyter-dash) (7.1.2)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from flask->jupyter-dash) (2.11.3)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from flask->jupyter-dash) (1.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2<3.0,>=2.10.1->flask->jupyter-dash) (2.0.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly>=5.0.0->dash->jupyter-dash) (8.1.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->ansi2html->jupyter-dash) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->ansi2html->jupyter-dash) (3.10.0)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.7/dist-packages (from ipykernel->jupyter-dash) (6.1.12)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipykernel->jupyter-dash) (6.0.4)
Requirement already satisfied: traitlets>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel->jupyter-dash) (5.1.1)
Collecting jedi>=0.10
  Downloading jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 49.8 MB/s
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from ipython->jupyter-dash) (2.0.10)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython->jupyter-dash) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython->jupyter-dash) (57.4.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython->jupyter-dash) (0.7.5)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython->jupyter-dash) (2.6.1)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython->jupyter-dash) (4.8.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython->jupyter-dash) (4.4.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.10->ipython->jupyter-dash) (0.8.3)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->jupyter-dash) (1.15.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->jupyter-dash) (0.2.5)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client->ipykernel->jupyter-dash) (23.2.1)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client->ipykernel->jupyter-dash) (4.11.2)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from jupyter-client->ipykernel->jupyter-dash) (2.8.2)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->ipython->jupyter-dash) (0.7.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->jupyter-dash) (2022.9.24)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->jupyter-dash) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->jupyter-dash) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->jupyter-dash) (2.10)
Building wheels for collected packages: retrying
  Building wheel for retrying (setup.py) ... done
  Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11448 sha256=b608afd1a7699e636cb0cf641e68c61e2373a665b05e66d25fe1dd5f8523a909
  Stored in directory: /root/.cache/pip/wheels/f9/8d/8d/f6af3f7f9eea3553bc2fe6d53e4b287dad18b06a861ac56ddf
Successfully built retrying
Installing collected packages: jedi, dash-table, dash-html-components, dash-core-components, retrying, nest-asyncio, dash, ansi2html, jupyter-dash
Successfully installed ansi2html-1.8.0 dash-2.7.0 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0 jedi-0.18.1 jupyter-dash-0.4.2 nest-asyncio-1.5.6 retrying-1.3.3

In [ ]:
import pandas as pd #U: leer y agrupar datos

In [ ]:
import plotly.graph_objects as go #U: graficar con plotly
import plotly.express as px #U: graficar con plotly

from jupyter_dash import JupyterDash #TODO: como se usa? necesitamos? #VER: https://analyticsindiamag.com/how-to-use-plotly-in-colab/
from dash import dcc
from dash import html
from dash.dependencies import Input, Output

## Obtener los datos

Ya los extraemos del sitio de BCRA y los guardamos en data.podemosaprender.org

* TODO: se podrían extraer para más años.
* TODO: se pueden agregar los de GCBA de m2
* TODO: se pueden agregar salarios, RIPTE?

In [ ]:
# creo tablas de UVIS
uvi_df_tables= pd.read_html('http://data.podemosaprender.org/finanzas/UVI_BCRA_2022.html')
uvi_df= uvi_df_tables[0] #A: sabemos que hay una sola
uvi_df

          Fecha   Valor
0    2022-01-01   99.84
1    2022-01-02   99.84
2    2022-01-03   99.84
3    2022-01-04  100.09
4    2022-01-05  100.16
..          ...     ...
314  2022-11-11  155.14
315  2022-11-12  155.47
316  2022-11-13  155.47
317  2022-11-14  155.47
318  2022-11-15  156.47

[319 rows x 2 columns]

In [ ]:
# creo tablas de UVAS
uva_df_tables= pd.read_html('http://data.podemosaprender.org/finanzas/UVA_BCRA_2022.html')
uva_df= uva_df_tables[0] #A: sabemos que hay una sola! PARA quer hace esto ?
uva_df

          Fecha   Valor
0    2022-01-01   97.58
1    2022-01-02   97.58
2    2022-01-03   97.58
3    2022-01-04   97.82
4    2022-01-05   97.89
..          ...     ...
314  2022-11-11  168.70
315  2022-11-12  169.03
316  2022-11-13  169.03
317  2022-11-14  169.03
318  2022-11-15  170.02

[319 rows x 2 columns]

In [ ]:
# creo tabla de dolar blue. Ojo!!! PQ   no tuve que usar la funcion pd.read_html 
usd_blue_df= pd.read_csv("https://data.podemosaprender.org/finanzas/USD_BLUE_2022.csv", sep="\t")
usd_blue_df

          fecha  compra  venta
0    2022-01-03   202.0  202.0
1    2022-01-04   202.5  202.5
2    2022-01-05   203.5  203.5
3    2022-01-06   204.5  204.5
4    2022-01-07   204.0  204.0
..          ...     ...    ...
213  2022-11-08   287.0  287.0
214  2022-11-09   288.0  288.0
215  2022-11-10   288.0  288.0
216  2022-11-11   289.0  289.0
217  2022-11-14   290.0  290.0

[218 rows x 3 columns]

In [ ]:
# me guardo el primer dato de la lista de dolar blue venta. Este seria mi dato cero con el cual comparo todos los demas
usd_blue_inicial = usd_blue_df['venta'][0]

In [ ]:
#inicializo como valor 100 % el primer valor  
usd_blue_df['indice']=usd_blue_df['venta'] / usd_blue_inicial *100
usd_blue_df.rename(columns={'fecha':'Fecha'}, inplace=True)# cambio el nombre de la columna 'fecha' a 'Fecha' 
usd_blue_df

          Fecha  compra  venta      indice
0    2022-01-03   202.0  202.0  100.000000
1    2022-01-04   202.5  202.5  100.247525
2    2022-01-05   203.5  203.5  100.742574
3    2022-01-06   204.5  204.5  101.237624
4    2022-01-07   204.0  204.0  100.990099
..          ...     ...    ...         ...
213  2022-11-08   287.0  287.0  142.079208
214  2022-11-09   288.0  288.0  142.574257
215  2022-11-10   288.0  288.0  142.574257
216  2022-11-11   289.0  289.0  143.069307
217  2022-11-14   290.0  290.0  143.564356

[218 rows x 4 columns]

In [ ]:
uvi_inicial = uvi_df['Valor'][0]

In [ ]:
uvi_df['indice'] = uvi_df['Valor'] / uvi_inicial * 100
uvi_df

          Fecha   Valor      indice
0    2022-01-01   99.84  100.000000
1    2022-01-02   99.84  100.000000
2    2022-01-03   99.84  100.000000
3    2022-01-04  100.09  100.250401
4    2022-01-05  100.16  100.320513
..          ...     ...         ...
314  2022-11-11  155.14  155.388622
315  2022-11-12  155.47  155.719151
316  2022-11-13  155.47  155.719151
317  2022-11-14  155.47  155.719151
318  2022-11-15  156.47  156.720753

[319 rows x 3 columns]

In [ ]:
uva_inicial = uva_df['Valor'][0]

In [ ]:

uva_df['indice']=uva_df['Valor']/uva_inicial*100
#uva_df.rename(columns={'fecha':'Fecha'}, inplace=True)
uva_df

          Fecha   Valor      indice
0    2022-01-01   97.58  100.000000
1    2022-01-02   97.58  100.000000
2    2022-01-03   97.58  100.000000
3    2022-01-04   97.82  100.245952
4    2022-01-05   97.89  100.317688
..          ...     ...         ...
314  2022-11-11  168.70  172.883788
315  2022-11-12  169.03  173.221972
316  2022-11-13  169.03  173.221972
317  2022-11-14  169.03  173.221972
318  2022-11-15  170.02  174.236524

[319 rows x 3 columns]

In [ ]:
#TODO: convertir todos en INDICES que valgan lo mismo en el primer dia ej. 100 y cambien proporcionalmente.
indices_df= pd.merge(uva_df, uvi_df, on="Fecha")
indices_df.rename(columns={'Valor_x':'UVA', 'Valor_y': 'UVI','indice_x':'UVA_index', 'indice_y':'UVI_index'}, inplace=True)

indices_df

          Fecha     UVA   UVA_index     UVI   UVI_index
0    2022-01-01   97.58  100.000000   99.84  100.000000
1    2022-01-02   97.58  100.000000   99.84  100.000000
2    2022-01-03   97.58  100.000000   99.84  100.000000
3    2022-01-04   97.82  100.245952  100.09  100.250401
4    2022-01-05   97.89  100.317688  100.16  100.320513
..          ...     ...         ...     ...         ...
314  2022-11-11  168.70  172.883788  155.14  155.388622
315  2022-11-12  169.03  173.221972  155.47  155.719151
316  2022-11-13  169.03  173.221972  155.47  155.719151
317  2022-11-14  169.03  173.221972  155.47  155.719151
318  2022-11-15  170.02  174.236524  156.47  156.720753

[319 rows x 5 columns]


De aca para abajo vamos a unir todos los idices

In [ ]:
#TODO: convertir todos en INDICES que valgan lo mismo en el primer dia ej. 100 y cambien proporcionalmente.
indices_df= pd.merge(indices_df, usd_blue_df, on="Fecha")
indices_df.rename(columns={'indice':'i_USD'}, inplace=True)
indices_df

,Fecha,UVA,UVA_index,UVI,UVI_index,compra,venta,i_USD
0,2022-01-03,97.58,100.000000,99.84,100.000000,202.0,202.0,100.000000
1,2022-01-04,97.82,100.245952,100.09,100.250401,202.5,202.5,100.247525
2,2022-01-05,97.89,100.317688,100.16,100.320513,203.5,203.5,100.742574
3,2022-01-06,97.97,100.399672,100.22,100.380609,204.5,204.5,101.237624
4,2022-01-07,98.05,100.481656,100.28,100.440705,204.0,204.0,100.990099
...,...,...,...,...,...,...,...,...
213,2022-11-08,167.72,171.879484,154.16,154.407051,287.0,287.0,142.079208
214,2022-11-09,168.05,172.217668,154.49,154.737580,288.0,288.0,142.574257
215,2022-11-10,168.38,172.555852,154.82,155.068109,288.0,288.0,142.574257
216,2022-11-11,168.70,172.883788,155.14,155.388622,289.0,289.0,143.069307
217,2022-11-14,169.03,173.221972,155.47,155.719151,290.0,290.0,143.564356

## Graficar una comparación básica

In [ ]:
fig = px.line(indices_df, x="Fecha", y=["UVA_index","UVI_index","i_USD"], title='Indice de precios Construcción (UVI) vs Consumidor (UVA) vs Dolar Blue')
fig.show()
#A: el grafico facilisimo y comodisimo que nos regala plotly <3 <3 <3

In [ ]:
#TODO: mas avanzado pero lento de ejecutar
fig = px.line(uva_df, x="Fecha", y="Valor")

app = JupyterDash(__name__) #A: podemos crear una app dash aca mismo!
app.layout = html.Div([dcc.Graph(figure=fig)]) #A: armamos la app como siempre en dash, con html, controles, etc.
app.run_server(mode='inline') #A: ejecutar la app aqui mismo